name: assign-labels

on:
  pull_request:
    branches: [ master ]

jobs:
  changedfiles:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    steps:
      - name: View modified files
        id: get_files
        uses: actions/github-script@v6
        with:
          script: |
            return github.rest.pulls.listFiles({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.pull_request.number
            });
        result-encoding: string
      - name: print output
        run: |
          echo '${{steps.get_files.outputs.result}}'

