name: validate-atomics

on:
  pull_request_target:
    branches:
      - master

jobs:
  validate-atomics:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - name: setup python3.11
        uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: "3.11.2"
          cache: "poetry"
      - name: Install dependencies
        run: poetry install --no-interaction --no-root
      - uses: actions/github-script@v6
        id: get_pr_number
        with:
          script: |
            if (context.issue.number) {
              // Return issue number if present
              return context.issue.number;
            } else {
              // Otherwise return issue number from commit
              return (
                await github.rest.repos.listPullRequestsAssociatedWithCommit({
                  commit_sha: context.sha,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                })
              ).data[0].number;
            }
          result-encoding: string
      - name: assign labels and reviewers
        run: |
          poetry run python bin/runner/runner.py -pr '${{steps.get_pr_number.outputs.result}}' -t  ${{ secrets.GITHUB_TOKEN }}
