name: validate-atomics

on:
  pull_request:
    branches: [ master ]

permissions: write-all

jobs:
  validate-atomics:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - name: setup python3.11
        uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: "3.11.2"
          cache: "poetry"
      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: validate the format of atomics tests against the spec
        run: |
          poetry run python bin/validate/validate.py

      - uses: actions/github-script@v6
        id: get_pr_number
        with:
          script: |
            if (context.issue.number) {
              // Return issue number if present
              return context.issue.number;
            } else {
              // Otherwise return issue number from commit
              return (
                await github.rest.repos.listPullRequestsAssociatedWithCommit({
                  commit_sha: context.sha,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                })
              ).data[0].number;
            }
          result-encoding: string
#      - name: assign labels and reviewers
#        env:
#          AUTO_ASSIGN_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        if: env.AUTO_ASSIGN_TOKEN
#        run: |
#          poetry run python bin/runner/runner.py -pr '${{steps.get_pr_number.outputs.result}}' -t "$AUTO_ASSIGN_TOKEN"
      - uses: actions/github-script@v6
        id: assign_labels_test
        with:
          github-token: ${{ secrets.AUTO_ASSIGN_TOKEN }}
          script: |            
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['windows']
            })
          result-encoding: string

  validate-terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -recursive -check
        continue-on-error: false